services:
  - type: web
    name: piston-api
    env: docker
    plan: standard
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    envVars:
      - key: PISTON_LOG_LEVEL
        value: INFO
      - key: PISTON_BIND_ADDRESS
        value: 0.0.0.0:$PORT
      - key: PISTON_DATA_DIRECTORY
        value: /tmp/piston
      - key: PISTON_DISABLE_NETWORKING
        value: "true"
    disk:
      name: piston-data
      mountPath: /tmp
      sizeGB: 10