services:
  - type: web
    name: piston-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    plan: standard
    branch: main
    healthCheckPath: /api/v2/runtimes
    envVars:
      - key: PISTON_BIND_ADDRESS
        value: "0.0.0.0:2000" 
      - key: PISTON_DATA_DIRECTORY
        value: /piston
      - key: PISTON_LOG_LEVEL
        value: INFO
      - key: PISTON_MAX_CONCURRENT_JOBS
        value: 64
      - key: PISTON_DISABLE_NETWORKING
        value: "true"
      - key: PISTON_OUTPUT_MAX_SIZE  
        value: 1024

    disk:
      name: piston-data
      mountPath: /piston
      sizeGB: 10

  - type: web
    name: piston-cli
    env: node
    buildCommand: cd cli && npm install
    startCommand: node cli/index.js
    plan: free
    envVars:
      - key: PISTON_URL 
        fromService:
          name: piston-api
          type: web
          property: host